apiVersion: app/v1
kind: deployment
metadata:
  name: k8-static
  namespace: static
spec:
  selector:
    matchlabel:
      app: static
  replicas: 1
  template: 
    metadata:
      labels:
        app: static
    spec:
      containers:
        -name: static
        image: 505280656844.dkr.ecr.us-east-2.amazonaws.com/k8s-static
        ports:
          -containerport: 80